"""Social Home — privacy-first federated social platform for Home Assistant.

See spec_work.md for the canonical specification.
"""

try:
    from ._version import __version__
except ImportError:  # pragma: no cover — non-installed source checkout
    # ``_version.py`` is generated by ``hatch-vcs`` during ``python
    # -m build`` and is not checked in (see .gitignore). When
    # running directly from a source checkout that hasn't been
    # built, fall back to a sentinel so imports still succeed.
    __version__ = "0.0.0+unknown"
