import { lazy } from 'preact-iso'

export const routes: Record<string, ReturnType<typeof lazy>> = {
  '/':               lazy(() => import('@/features/feed/LandingDispatch')),
  '/feed':           lazy(() => import('@/features/feed/FeedPage')),
  '/spaces':         lazy(() => import('@/features/spaces/SpaceListPage')),
  '/spaces/browse':  lazy(() => import('@/features/spaces/SpaceBrowserPage')),
  '/spaces/:id':     lazy(() => import('@/features/spaces/SpaceFeedPage')),
  '/spaces/:id/settings': lazy(() => import('@/features/spaces/SpaceSettingsPage')),
  '/spaces/:id/zones': lazy(() => import('@/features/spaces/SpaceZonesPage')),
  '/join':           lazy(() => import('@/features/spaces/SpaceJoinLanding')),
  '/dms':            lazy(() => import('@/features/dms/DmInboxPage')),
  '/dms/:id':        lazy(() => import('@/features/dms/DmThreadPage')),
  '/dms/:id/calls':  lazy(() => import('@/features/dms/CallHistoryPane')),
  '/calendar':       lazy(() => import('@/features/calendar/CalendarPage')),
  // Tasks · Shopping · Stickies share a single Organize hub now —
  // each was its own routed page that crowded the AT-HOME sidebar.
  '/organize':       lazy(() => import('@/features/organize/OrganizePage')),
  '/presence':       lazy(() => import('@/features/presence/PresencePage')),
  '/settings':       lazy(() => import('@/features/settings/SettingsPage')),
  '/corner':         lazy(() => import('@/features/dashboard/DashboardPage')),
  '/dashboard':      lazy(() => import('@/features/dashboard/DashboardRedirect')),
  '/notifications':  lazy(() => import('@/features/notifications/NotificationsPage')),
  '/pages':          lazy(() => import('@/features/pages/PagesPage')),
  '/bazaar':         lazy(() => import('@/features/bazaar/BazaarPage')),
  '/admin':          lazy(() => import('@/features/admin/AdminPage')),
  '/connections':    lazy(() => import('@/features/connections/ConnectionsPage')),
  '/friends':        lazy(() => import('@/features/friends/FriendsPage')),
  '/gallery':        lazy(() => import('@/features/gallery/GalleryPage')),
  '/search':         lazy(() => import('@/features/search/SearchPage')),
  '/calls':          lazy(() => import('@/features/calls/CallsRedirect')),
  '/calls/:callId':  lazy(() => import('@/features/calls/InCallPage')),
  '/highlights':        lazy(() => import('@/features/highlights/HighlightsPage')),
  '/highlights/archive': lazy(() => import('@/features/highlights/HighlightArchiveRedirect')),
  '/highlights/new':    lazy(() => import('@/features/highlights/HighlightComposerPage')),
  '/highlights/:highlightId': lazy(() => import('@/features/highlights/HighlightViewerPage')),
  '/momentum':              lazy(() => import('@/features/momentum/MomentumPage')),
  '/momentum/archive':      lazy(() => import('@/features/momentum/MomentumArchiveRedirect')),
  '/momentum/new':          lazy(() => import('@/features/momentum/MomentumComposerRedirect')),
  '/momentum/public/discover': lazy(() => import('@/features/momentum/PublicDiscoveryPage')),
  '/momentum/public/sharing':  lazy(() => import('@/features/momentum/PublicSharingSettings')),
  '/momentum/:momentId':    lazy(() => import('@/features/momentum/MomentumDetailPage')),
  '/momentum/:momentId/reply': lazy(() => import('@/features/momentum/MomentumComposerRedirect')),
  '/parent':         lazy(() => import('@/features/child-protection/ParentDashboard')),
  '/setup':          lazy(() => import('@/features/setup/SetupPage')),
}
