"""Golden-bytes test for the public-story DataChannel framing protocol.

Release-blocker per CLAUDE.md §27.9 — every wire format change must
update this file in the same commit. The expected byte sequences are
generated by the reference encoder; we re-decode them and assert
field-by-field equality so a refactor on either side surfaces here
immediately.
"""

from __future__ import annotations

import json
import struct

import pytest

from socialhome.services.story_public_framing import (
    CHANNEL_LABEL,
    CHUNK_SIZE,
    KIND_ERROR,
    KIND_FRAME_CHUNK,
    KIND_STORY_META,
    KIND_STREAM_END,
    SEND_HWM_BYTES,
    Frame,
    FramingError,
    decode,
    encode,
    error_frame,
    frame_chunk,
    iter_frames,
    stream_end,
    story_meta,
)


# ─── Wire constants ──────────────────────────────────────────────────────


def test_wire_constants_are_locked():
    """These bytes are part of the wire contract — change in lockstep
    with the JS bootstrap and the public-viewer release notes."""
    assert CHANNEL_LABEL == "story-public-v1"
    assert CHUNK_SIZE == 64 * 1024
    assert SEND_HWM_BYTES == 1 << 20
    assert KIND_STORY_META == "story_meta"
    assert KIND_FRAME_CHUNK == "frame_chunk"
    assert KIND_STREAM_END == "stream_end"
    assert KIND_ERROR == "error"


# ─── Encoder shape ───────────────────────────────────────────────────────


def test_encode_lays_out_u32_header_len_then_header_then_u32_payload_len():
    """The wire format is `[u32 header_len BE][header][u32 payload_len BE][payload]`.

    We hand-pack the same shape and compare byte-for-byte so a future
    refactor that reorders fields breaks here loudly.
    """
    payload = b"abc"
    raw = frame_chunk(
        frame_id="f-1",
        sequence=0,
        chunk_index=0,
        byte_length=3,
        is_last_chunk=True,
        payload=payload,
    )
    # Re-construct what the wire MUST look like.
    expected_header = json.dumps(
        {
            "byte_length": 3,
            "chunk_index": 0,
            "frame_id": "f-1",
            "is_last_chunk": True,
            "kind": KIND_FRAME_CHUNK,
            "sequence": 0,
        },
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    expected = (
        struct.pack(">I", len(expected_header))
        + expected_header
        + struct.pack(">I", len(payload))
        + payload
    )
    assert raw == expected


def test_story_meta_carries_full_story_and_manifest():
    raw = story_meta(
        {"id": "s-1", "author_user_id": "u1"},
        [{"frame_id": "f-1", "sequence": 0, "byte_length": 100}],
    )
    decoded = decode(raw)
    assert decoded.header["kind"] == KIND_STORY_META
    assert decoded.header["story"]["id"] == "s-1"
    assert decoded.header["frames"][0]["frame_id"] == "f-1"
    assert decoded.payload == b""


def test_stream_end_has_empty_payload():
    decoded = decode(stream_end())
    assert decoded.header == {"kind": KIND_STREAM_END}
    assert decoded.payload == b""


def test_error_frame_carries_reason():
    decoded = decode(error_frame("expired"))
    assert decoded.header == {"kind": KIND_ERROR, "error": "expired"}


# ─── Decode round-trip + iter_frames ─────────────────────────────────────


def test_round_trip_for_every_kind():
    """Encode + decode for each frame kind preserves the header exactly."""
    cases: list[Frame] = [
        Frame(header={"kind": KIND_STREAM_END}, payload=b""),
        Frame(header={"kind": KIND_ERROR, "error": "backpressure"}, payload=b""),
    ]
    for case in cases:
        raw = encode(case.header, case.payload)
        out = decode(raw)
        assert out == case


def test_iter_frames_yields_every_frame_in_order():
    one = story_meta({"id": "s"}, [])
    two = frame_chunk(
        frame_id="f",
        sequence=0,
        chunk_index=0,
        byte_length=4,
        is_last_chunk=True,
        payload=b"data",
    )
    three = stream_end()
    out = list(iter_frames(one + two + three))
    assert [f.header["kind"] for f in out] == [
        KIND_STORY_META,
        KIND_FRAME_CHUNK,
        KIND_STREAM_END,
    ]
    assert out[1].payload == b"data"


# ─── Failure modes ───────────────────────────────────────────────────────


def test_decode_rejects_unknown_kind():
    with pytest.raises(FramingError):
        encode({"kind": "wrong"}, b"")


def test_decode_rejects_zero_length_header():
    with pytest.raises(FramingError):
        decode(struct.pack(">I", 0))


def test_decode_rejects_truncated_header():
    with pytest.raises(FramingError):
        decode(b"\x00\x00\x00")  # less than 4 bytes


def test_decode_rejects_truncated_payload():
    raw = frame_chunk(
        frame_id="f",
        sequence=0,
        chunk_index=0,
        byte_length=10,
        is_last_chunk=False,
        payload=b"short",
    )
    # Drop the last 2 bytes of the payload.
    with pytest.raises(FramingError):
        decode(raw[:-2])


def test_decode_rejects_invalid_json_header():
    raw = struct.pack(">I", 4) + b"{bad" + struct.pack(">I", 0)
    with pytest.raises(FramingError):
        decode(raw)


def test_iter_frames_rejects_trailing_partial_frame():
    raw = stream_end() + b"\x00\x00"
    with pytest.raises(FramingError):
        list(iter_frames(raw))


def test_encode_rejects_non_bytes_payload():
    with pytest.raises(FramingError):
        encode({"kind": KIND_FRAME_CHUNK}, "not-bytes")  # type: ignore[arg-type]
